version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: later
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d later"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        PGPASSWORD=12345 psql -U dbuser -h db -d later -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          email VARCHAR(320),
          first_name VARCHAR(100),
          last_name VARCHAR(100),
          registration_date TIMESTAMP,
          state VARCHAR(50)
        );
        
        CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          user_id BIGINT,
          url VARCHAR(1000),
          CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id),
          UNIQUE(id, url)
        );
        
        CREATE TABLE IF NOT EXISTS tags (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          item_id BIGINT,
          name VARCHAR(50),
          CONSTRAINT fk_tags_to_items FOREIGN KEY(item_id) REFERENCES items(id)
        );
        CREATE TABLE IF NOT EXISTS item_notes (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          item_id BIGINT,
          text VARCHAR(1000),
          note_date TIMESTAMP,
          CONSTRAINT items FOREIGN KEY(item_id) REFERENCES items(id)
        );
        EOSQL
    restart: "no"
